language: node_js
node_js: lts/*
sudo: false
install:
  - npm install
  - npm install firebase
  - npm install react-firebaseui
  - npm run build

script: 'true'

deploy:
  skip_cleanup: true
  provider: firebase

